# Generated by Django 4.0 on 2022-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_comments', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='engagement',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
